"
wbh 99
"
Class {
	#name : 'Hydrographics',
	#superclass : 'Object',
	#instVars : [
		'code',
		'distribution'
	],
	#category : 'Traveller-WorldBuildersHandbook',
	#package : 'Traveller-WorldBuildersHandbook'
}

{ #category : 'accessing' }
Hydrographics >> code [

	^ code
]

{ #category : 'accessing' }
Hydrographics >> code: anObject [

	code := anObject
]

{ #category : 'accessing' }
Hydrographics >> distribution [

	^ distribution
]

{ #category : 'accessing' }
Hydrographics >> distribution: anObject [

	distribution := anObject
]
