"
wbh 99
"
Class {
	#name : 'Hydrographics',
	#superclass : 'Object',
	#instVars : [
		'code',
		'distribution',
		'percent',
		'liquid'
	],
	#category : 'Traveller-WorldBuildersHandbook',
	#package : 'Traveller-WorldBuildersHandbook'
}

{ #category : 'accessing' }
Hydrographics >> code [

	^ code
]

{ #category : 'accessing' }
Hydrographics >> code: anObject [

	code := anObject
]

{ #category : 'accessing' }
Hydrographics >> distribution [

	^ distribution
]

{ #category : 'accessing' }
Hydrographics >> distribution: anObject [

	distribution := anObject
]

{ #category : 'accessing' }
Hydrographics >> liquid [

	^ liquid
]

{ #category : 'accessing' }
Hydrographics >> liquid: anObject [

	liquid := anObject
]

{ #category : 'accessing' }
Hydrographics >> percent [

	^ percent
]

{ #category : 'accessing' }
Hydrographics >> percent: anObject [

	percent := anObject
]
