"
Standard UWP codes
"
Trait {
	#name : 'UWP',
	#instVars : [
		'starport',
		'sizeCode',
		'atmosphereCode',
		'hydrographicsCode',
		'populationCode',
		'governmentCode',
		'lawLevelCode',
		'techLevelCode'
	],
	#category : 'Traveller',
	#package : 'Traveller'
}

{ #category : 'accessing' }
UWP >> atmosphereCode [

	^ atmosphereCode
]

{ #category : 'accessing' }
UWP >> atmosphereCode: anObject [

	atmosphereCode := anObject
]

{ #category : 'accessing' }
UWP >> governmentCode [

	^ governmentCode
]

{ #category : 'accessing' }
UWP >> governmentCode: anObject [

	governmentCode := anObject
]

{ #category : 'accessing' }
UWP >> hydrographicsCode [

	^ hydrographicsCode
]

{ #category : 'accessing' }
UWP >> hydrographicsCode: anObject [

	hydrographicsCode := anObject
]

{ #category : 'accessing' }
UWP >> lawLevelCode [

	^ lawLevelCode
]

{ #category : 'accessing' }
UWP >> lawLevelCode: anObject [

	lawLevelCode := anObject
]

{ #category : 'accessing' }
UWP >> populationCode [

	^ populationCode
]

{ #category : 'accessing' }
UWP >> populationCode: anObject [

	populationCode := anObject
]

{ #category : 'accessing' }
UWP >> sizeCode [

	^ sizeCode
]

{ #category : 'accessing' }
UWP >> sizeCode: anObject [

	sizeCode := anObject
]

{ #category : 'accessing' }
UWP >> starport [

	^ starport
]

{ #category : 'accessing' }
UWP >> starport: anObject [

	starport := anObject
]

{ #category : 'accessing' }
UWP >> techLevelCode [

	^ techLevelCode
]

{ #category : 'accessing' }
UWP >> techLevelCode: anObject [

	techLevelCode := anObject
]
